# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wmz08zSPEffmM2mYmoofPxsOzLyLJjmL
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
image_path = 'ab.png'
image = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
if image is None:
    print("Error: Unable to load image. Please check the file path.")
else:
    if image.shape[2] == 4:
        bgr_image = cv2.cvtColor(image, cv2.COLOR_BGRA2BGR)
    else:
        bgr_image = image
    mask = np.zeros(bgr_image.shape[:2], np.uint8)
    background_model = np.zeros((1, 65), np.float64)
    foreground_model = np.zeros((1, 65), np.float64)
    rectangle = (150, 50, bgr_image.shape[1] - 50, bgr_image.shape[0] - 50)
    cv2.grabCut(bgr_image, mask, rectangle, background_model, foreground_model, 5, cv2.GC_INIT_WITH_RECT)
    mask2 = np.where((mask == 2) | (mask == 0), 0, 1).astype('uint8')
    result = bgr_image * mask2[:, :, np.newaxis]
    result[mask2 == 0] = [255, 255, 255]
    plt.imshow(cv2.cvtColor(result, cv2.COLOR_BGR2RGB))
    plt.title('Background Removed')
    plt.axis('off')
    plt.show()